//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokTakipSistemiDBEntities : DbContext
    {
        public StokTakipSistemiDBEntities()
            : base("name=StokTakipSistemiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAtikKontrol> tblAtikKontrol { get; set; }
        public virtual DbSet<tblDepartman> tblDepartman { get; set; }
        public virtual DbSet<tblKullanıcı> tblKullanıcı { get; set; }
        public virtual DbSet<tblParcaTipi> tblParcaTipi { get; set; }
        public virtual DbSet<tblPersonel> tblPersonel { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblStok> tblStok { get; set; }
        public virtual DbSet<tblUrun> tblUrun { get; set; }
        public virtual DbSet<tblUrunGenel> tblUrunGenel { get; set; }
        public virtual DbSet<tblZimmet> tblZimmet { get; set; }
    }
}
