//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtikKontrol
    {
        public int atikKontrolId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> atikurunAdet { get; set; }
    
        public virtual tblUrun tblUrun { get; set; }
    }
}
