//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanıcı
    {
        public int kullanıcıId { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<System.DateTime> sonGirisTarihi { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
