//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunGenel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrunGenel()
        {
            this.tblStok = new HashSet<tblStok>();
            this.tblUrun = new HashSet<tblUrun>();
        }
    
        public int urunGenelId { get; set; }
        public string urunAd { get; set; }
        public Nullable<System.DateTime> urunSatinAlmaTarih { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<decimal> urunToplamFİyat { get; set; }
        public Nullable<int> urunParcaId { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public Nullable<int> urunAdet { get; set; }
        public string satinAlinanKurum { get; set; }
    
        public virtual tblParcaTipi tblParcaTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStok> tblStok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUrun> tblUrun { get; set; }
    }
}
