//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrun()
        {
            this.tblAtikKontrol = new HashSet<tblAtikKontrol>();
            this.tblZimmet = new HashSet<tblZimmet>();
        }
    
        public int urunId { get; set; }
        public string urunAd { get; set; }
        public Nullable<System.DateTime> urunSatinAlmaTarih { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<int> urunParcaId { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public string satinAlinanKurum { get; set; }
        public Nullable<bool> zimmetDurumu { get; set; }
        public int urunGenelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtikKontrol> tblAtikKontrol { get; set; }
        public virtual tblUrunGenel tblUrunGenel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZimmet> tblZimmet { get; set; }
    }
}
