//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departmanlar
    {
        public Departmanlar()
        {
            this.Personeller = new HashSet<Personeller>();
        }
    
        public int departmanID { get; set; }
        public string departmanAdi { get; set; }
    
        public virtual ICollection<Personeller> Personeller { get; set; }
    }
}
