//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public int kisiID { get; set; }
        public string adi { get; set; }
        public string cepTelefonu { get; set; }
        public Nullable<int> departmanID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<int> zimmetID { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual Zimmetler Zimmetler { get; set; }
    }
}
