//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public Kullanıcılar()
        {
            this.Zimmetler = new HashSet<Zimmetler>();
        }
    
        public int kullaniciID { get; set; }
        public string kullaniciAdi { get; set; }
        public Nullable<int> kullaniciSifre { get; set; }
        public Nullable<int> rolID { get; set; }
    
        public virtual Roller Roller { get; set; }
        public virtual ICollection<Zimmetler> Zimmetler { get; set; }
    }
}
