//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roller
    {
        public Roller()
        {
            this.Kullanıcılar = new HashSet<Kullanıcılar>();
        }
    
        public int rolID { get; set; }
        public string roller1 { get; set; }
    
        public virtual ICollection<Kullanıcılar> Kullanıcılar { get; set; }
    }
}
