//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmetler
    {
        public Zimmetler()
        {
            this.Kisiler = new HashSet<Kisiler>();
        }
    
        public int zimmetID { get; set; }
        public Nullable<System.DateTime> zimmetTarihi { get; set; }
        public Nullable<bool> zimmetDurum { get; set; }
        public Nullable<int> zimmetlenenID { get; set; }
    
        public virtual ICollection<Kisiler> Kisiler { get; set; }
        public virtual ZimmetDetay ZimmetDetay { get; set; }
    }
}
