//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmetlenenler
    {
        public int zimmetlenenID { get; set; }
        public string zimmetlenenAd { get; set; }
        public string adres { get; set; }
        public string cepTelefonu { get; set; }
    }
}
