//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZimmetDetay
    {
        public int zimmetID { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<int> miktar { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Zimmetler Zimmetler { get; set; }
    }
}
